server:
  port: 8004
  
spring:
  application:
    name: RATING-SERVICE

#spring.config.import= configserver:property    
  config:
    import:
    - optional:configserver:http://localhost:8000
        
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: hms-hotel_db
    
#eureka:
#  instance:
#    hostname: localhost
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultzone: http://localhost:8761/eureka